services:
  - type: web
    name: rs-wayfinding-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://yaumulutd_db_user:yaumulharby1@cluster0.troe5ef.mongodb.net/?appName=Cluster0
      - key: DB_NAME
        value: rs_wayfinding
      - key: CORS_ORIGINS
        value: https://rs-wayfinding2.netlify.app
    healthCheckPath: /api/
